<?php

namespace AppBundle\Repository;

/**
 * IndustryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryRepository extends \Doctrine\ORM\EntityRepository
{
}
